[package]
name = "rterm-types"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
rssh-types = { git = "file:///H:/project/R-SSH-split-trial/R-SSH", rev = "c2c515df0e532271abe32aac63c62b91fc75864d" }

[lints]
workspace = true
