[package]
name = "rterm-ssh-adapter"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "rssh_ssh"

[features]
runtime-adapter = []

[dependencies]
ssh-core = { package = "rssh-ssh", git = "https://github.com/a1112/R-SSH.git", rev = "3fdda8299ff6e066b4272a7a064d135e3be38647" }
rterm-runtime = { path = "../rssh-runtime", version = "0.1.0" }
rterm-types = { path = "../rterm-types", version = "0.1.0", features = ["ssh"] }

[dev-dependencies]
rssh-domain = { path = "../rssh-domain", version = "0.1.0" }

[lints]
workspace = true
